CREATE TABLE IF NOT EXISTS diary(
    id SERIAL PRIMARY KEY,
    diary_name VARCHAR(50) UNIQUE NOT NULL,
    email VARCHAR(255) UNIQUE,
    password VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
